version: '3.9'

services:
  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ~/apps/postgres/data:/app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  csvloader:
    build: ./csvloader
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    volumes:
      - ./csvloader:/app
  notebook:
    image: jupyter/minimal-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    command: "start-notebook.sh --NotebookApp.token="
